title: Kenyon Ng
url: "https://kenyon.xyz"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana, last updated on 30 March 2020"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "Research"
   link: "research"
 - name: "CV"
   link: "cv-no-contact.pdf"
 - name: "Contact"
   link: "contact"

